export const initalClues = {
    tutorial: [{
        id: 1,
        name: "poster",
        opened: false,
        solved: false,
        password: "Le freak",
        vidURL: 'unitex/tutorial/poster.mp4',
        picURL: 'unitex/tutorial/poster.png',
        reward: 'unitex/rewards/Bride.png',
        },
        {
        id: 2,
        name: "aed",
        opened: false,
        solved: false,
        password: "c'est chic",
        vidURL: "unitex/tutorial/AED.mp4",
        picURL: 'unitex/tutorial/AED Clue.png',
        reward: 'unitex/rewards/Ox.png',
        }
    ],
    gold: [{
        id: 1,
        name: "fire ext",
        opened: false,
        solved: false,
        password: "3fightready",
        vidURL: 'unitex/gold/fire exting.mp4',
        picURL: 'unitex/gold/fire extinguisher.png',
        reward: 'unitex/rewards/Ski.png',
        },
        {
        id: 2,
        name: "evac map",
        opened: false,
        solved: false,
        password: "morning49roll",
        vidURL: 'unitex/gold/map.mp4',
        picURL: 'unitex/gold/evacuation map.png',
        reward: 'unitex/rewards/Tie.png',
        },
        {
        id: 3,
        name: "pull station",
        opened: false,
        solved: false,
        password: "inventquick37",
        vidURL: 'unitex/gold/pull station.mp4',
        picURL: 'unitex/gold/pull.png',
        reward: 'unitex/rewards/ear.png',
        },
        {
        id: 4,
        name: "primary",
        opened: false,
        solved: false,
        password: "cloud65laugh",
        vidURL: 'unitex/gold/primary evac.mp4',
        picURL: 'unitex/gold/primary evac route.png',
        reward: 'unitex/rewards/goat.png',
        },
        {
        id: 5,
        name: "secondary",
        opened: false,
        solved: false,
        password: "frontnature40",
        vidURL: 'unitex/gold/secondary.png',
        picURL: 'unitex/gold/secondary.png',
        reward: 'unitex/rewards/hat.png',
        }
    ],
    green: [{
        id: 1,
        name: "drop cover",
        opened: false,
        solved: false,
        password: "surprisefood88",
        vidURL: 'unitex/green/dropcoverhold.mp4',
        picURL: 'unitex/green/drop cover hold.png',
        reward: 'unitex/rewards/lizard.png',
        },
        {
        id: 2,
        name: "SWSA",
        opened: false,
        solved: false,
        password: "shop82main",
        vidURL: 'unitex/green/shelter location.mp4',
        picURL: 'unitex/green/SWSA.png',
        reward: 'unitex/rewards/outside.png',
        },
        {
        id: 3,
        name: "evac map",
        opened: false,
        solved: false,
        password: "repeathow49",
        vidURL: 'unitex/green/map.mp4',
        picURL: 'unitex/green/evacuation map.png',
        reward: 'unitex/rewards/rain.png',
        },
        {
        id: 4,
        name: "primary",
        opened: false,
        solved: false,
        password: "wild60store",
        vidURL: 'unitex/green/primary evac.mp4',
        picURL: 'unitex/green/primary evac route.png',
        reward: 'unitex/rewards/slide.png',
        },
        {
        id: 5,
        name: "secondary",
        opened: false,
        solved: false,
        password: "lost34dance",
        vidURL: 'unitex/green/secondary.png',
        picURL: 'unitex/green/secondary.png',
        reward: 'unitex/rewards/star.png',
        }
    ]
}


export const overlordLogin = {
    username: "overlord",
    password: "evilINC"
}